### ISSUE TITLE
RGB14_v3 items are decoded incorrectly

### ISSUE THREAD

**Issue by stijn-vranckx** [mreutegg/laszip4j#142]
The color values are incorrect. See https://github.com/mreutegg/laszip4j/pull/141 for a possible fix and a file to reproduce the issue.

**Comment by mreutegg** [comment]
Thank you for reporting this issue and a file to reproduce.

As you hinted already in #141, the problem seems to be caused by `context` being passed by value to `LASreadItem.read()` and `LASreadItemCompressed.init()`.

#143 introduces a `MutableInteger` and uses it as type for the `context` parameters. With these changes the laz file available via #141 translates into a same las file as with LASTools.

@stijn-vranckx, can you please give it a try as well? I'd also like to add the laz file referenced in #141 as a test resource. What is the license for that file?

**Comment by stijn-vranckx** [comment]
@mreutegg For the license:

This pointcloud was captured by Hexagon airborne sensors and processed using Hexagon's ERDAS IMAGINE software. The small LAZ chip exported can be used for software test coverage and can be considered under CC-BY since the dataset is so small.

So I think the fiel can be added as a test resource.
I gave it a try and it is also working on my site.

**Comment by mreutegg** [comment]
Thank you for testing #143. I added the file as a test resource and there is now a test using it.

The fix will be available in laszip4j 0.19
